spring:
  application:
    name: ticketing
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/ticketing_springboot
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jackson:
    default-property-inclusion: non_null
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
springfox:
  documentation:
    swagger-ui:
      enabled: true
